apiVersion: v1
kind: Secret
metadata:
  name: gitea-inline-config
  namespace: "gitea"
  labels:
    app: gitea
    app.kubernetes.io/name: gitea
type: Opaque
stringData:
  _generals_: ""
  cache: |-
    ADAPTER=memory
    HOST=
  database: |-
    DB_TYPE=postgres
    HOST=postgresql.gitea.svc.cluster.local:5432
    NAME=gitea
    PASSWD=gitea
    USER=gitea
  indexer: ISSUE_INDEXER_TYPE=db
  metrics: ENABLED=false
  queue: |-
    CONN_STR=
    TYPE=level
  repository: ROOT=/data/git/gitea-repositories
  security: INSTALL_LOCK=true
  server: |-
    APP_DATA_PATH=/data
    DOMAIN=git.apps.ocp-hub.r301.telco.stc
    ENABLE_PPROF=false
    HTTP_PORT=3000
    PROTOCOL=http
    ROOT_URL=http://git.apps.ocp-hub.r301.telco.stc
    SSH_DOMAIN=git.apps.ocp-hub.r301.telco.stc
    SSH_LISTEN_PORT=2222
    SSH_PORT=22
    START_SSH_SERVER=true
  session: |-
    PROVIDER=memory
    PROVIDER_CONFIG=
